//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLauncher_Console.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_prevent_exit {
            get {
                return ((bool)(this["flag_prevent_exit"]));
            }
            set {
                this["flag_prevent_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_do_not_save_interface_changes {
            get {
                return ((bool)(this["flag_do_not_save_interface_changes"]));
            }
            set {
                this["flag_do_not_save_interface_changes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_always_scan_for_new_games {
            get {
                return ((bool)(this["flag_always_scan_for_new_games"]));
            }
            set {
                this["flag_always_scan_for_new_games"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_only_allow_command_line {
            get {
                return ((bool)(this["flag_only_allow_command_line"]));
            }
            set {
                this["flag_only_allow_command_line"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_typing_input_is_default {
            get {
                return ((bool)(this["flag_typing_input_is_default"]));
            }
            set {
                this["flag_typing_input_is_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_single_column_list_is_default {
            get {
                return ((bool)(this["flag_single_column_list_is_default"]));
            }
            set {
                this["flag_single_column_list_is_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_do_not_split_over_pages {
            get {
                return ((bool)(this["flag_do_not_split_over_pages"]));
            }
            set {
                this["flag_do_not_split_over_pages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_enlarge_height_to_fit {
            get {
                return ((bool)(this["flag_enlarge_height_to_fit"]));
            }
            set {
                this["flag_enlarge_height_to_fit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_sort_alphabetically {
            get {
                return ((bool)(this["flag_sort_alphabetically"]));
            }
            set {
                this["flag_sort_alphabetically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_sort_favourites_on_top {
            get {
                return ((bool)(this["flag_sort_favourites_on_top"]));
            }
            set {
                this["flag_sort_favourites_on_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flag_sort_not_installed_on_bottom {
            get {
                return ((bool)(this["flag_sort_not_installed_on_bottom"]));
            }
            set {
                this["flag_sort_not_installed_on_bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_colour_light_mode_is_default {
            get {
                return ((bool)(this["flag_colour_light_mode_is_default"]));
            }
            set {
                this["flag_colour_light_mode_is_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_always_show_all_games {
            get {
                return ((bool)(this["flag_always_show_all_games"]));
            }
            set {
                this["flag_always_show_all_games"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flag_do_not_show_settings_in_platform_list {
            get {
                return ((bool)(this["flag_do_not_show_settings_in_platform_list"]));
            }
            set {
                this["flag_do_not_show_settings_in_platform_list"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_do_not_scan_not_installed_games {
            get {
                return ((bool)(this["flag_do_not_scan_not_installed_games"]));
            }
            set {
                this["flag_do_not_scan_not_installed_games"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_only_scan_custom_games {
            get {
                return ((bool)(this["flag_only_scan_custom_games"]));
            }
            set {
                this["flag_only_scan_custom_games"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_text_use_custom_text_values {
            get {
                return ((bool)(this["flag_text_use_custom_text_values"]));
            }
            set {
                this["flag_text_use_custom_text_values"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_image_draw_border_characters {
            get {
                return ((bool)(this["flag_image_draw_border_characters"]));
            }
            set {
                this["flag_image_draw_border_characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_image_do_not_use_custom {
            get {
                return ((bool)(this["flag_image_do_not_use_custom"]));
            }
            set {
                this["flag_image_do_not_use_custom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_image_ignore_custom_aspect_ratio {
            get {
                return ((bool)(this["flag_image_ignore_custom_aspect_ratio"]));
            }
            set {
                this["flag_image_ignore_custom_aspect_ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_image_use_legacy_background_colours {
            get {
                return ((bool)(this["flag_image_use_legacy_background_colours"]));
            }
            set {
                this["flag_image_use_legacy_background_colours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_image_do_not_do_deep_scan_for_icons {
            get {
                return ((bool)(this["flag_image_do_not_do_deep_scan_for_icons"]));
            }
            set {
                this["flag_image_do_not_do_deep_scan_for_icons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public ushort num_list_icons_max_size_in_characters {
            get {
                return ((ushort)(this["num_list_icons_max_size_in_characters"]));
            }
            set {
                this["num_list_icons_max_size_in_characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public ushort num_list_icons_resolution {
            get {
                return ((ushort)(this["num_list_icons_resolution"]));
            }
            set {
                this["num_list_icons_resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public ushort num_selected_image_max_size_in_characters {
            get {
                return ((ushort)(this["num_selected_image_max_size_in_characters"]));
            }
            set {
                this["num_selected_image_max_size_in_characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public ushort num_selected_image_icon_resolution {
            get {
                return ((ushort)(this["num_selected_image_icon_resolution"]));
            }
            set {
                this["num_selected_image_icon_resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort num_selected_image_y_location_percent {
            get {
                return ((ushort)(this["num_selected_image_y_location_percent"]));
            }
            set {
                this["num_selected_image_y_location_percent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public ushort num_grid_text_min_column_characters {
            get {
                return ((ushort)(this["num_grid_text_min_column_characters"]));
            }
            set {
                this["num_grid_text_min_column_characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int num_steam_id {
            get {
                return ((int)(this["num_steam_id"]));
            }
            set {
                this["num_steam_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string colour_background {
            get {
                return ((string)(this["colour_background"]));
            }
            set {
                this["colour_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string colour_background_lightmode {
            get {
                return ((string)(this["colour_background_lightmode"]));
            }
            set {
                this["colour_background_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string colour_title {
            get {
                return ((string)(this["colour_title"]));
            }
            set {
                this["colour_title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public string colour_title_lightmode {
            get {
                return ((string)(this["colour_title_lightmode"]));
            }
            set {
                this["colour_title_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public string colour_subtitle {
            get {
                return ((string)(this["colour_subtitle"]));
            }
            set {
                this["colour_subtitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public string colour_subtitle_lightmode {
            get {
                return ((string)(this["colour_subtitle_lightmode"]));
            }
            set {
                this["colour_subtitle_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public string colour_entries {
            get {
                return ((string)(this["colour_entries"]));
            }
            set {
                this["colour_entries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string colour_entries_lightmode {
            get {
                return ((string)(this["colour_entries_lightmode"]));
            }
            set {
                this["colour_entries_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public string colour_entries_not_installed {
            get {
                return ((string)(this["colour_entries_not_installed"]));
            }
            set {
                this["colour_entries_not_installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public string colour_entries_not_installed_lightmode {
            get {
                return ((string)(this["colour_entries_not_installed_lightmode"]));
            }
            set {
                this["colour_entries_not_installed_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public string colour_highlight_background {
            get {
                return ((string)(this["colour_highlight_background"]));
            }
            set {
                this["colour_highlight_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string colour_highlight_background_lightmode {
            get {
                return ((string)(this["colour_highlight_background_lightmode"]));
            }
            set {
                this["colour_highlight_background_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string colour_highlight_text {
            get {
                return ((string)(this["colour_highlight_text"]));
            }
            set {
                this["colour_highlight_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string colour_highlight_text_lightmode {
            get {
                return ((string)(this["colour_highlight_text_lightmode"]));
            }
            set {
                this["colour_highlight_text_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public string colour_input_background {
            get {
                return ((string)(this["colour_input_background"]));
            }
            set {
                this["colour_input_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string colour_input_background_lightmode {
            get {
                return ((string)(this["colour_input_background_lightmode"]));
            }
            set {
                this["colour_input_background_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string colour_input_prompt {
            get {
                return ((string)(this["colour_input_prompt"]));
            }
            set {
                this["colour_input_prompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public string colour_input_prompt_lightmode {
            get {
                return ((string)(this["colour_input_prompt_lightmode"]));
            }
            set {
                this["colour_input_prompt_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string colour_error_background {
            get {
                return ((string)(this["colour_error_background"]));
            }
            set {
                this["colour_error_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string colour_error_background_lightmode {
            get {
                return ((string)(this["colour_error_background_lightmode"]));
            }
            set {
                this["colour_error_background_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public string colour_error_text {
            get {
                return ((string)(this["colour_error_text"]));
            }
            set {
                this["colour_error_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string colour_error_text_lightmode {
            get {
                return ((string)(this["colour_error_text_lightmode"]));
            }
            set {
                this["colour_error_text_lightmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftArrow")]
        public string key_left_1 {
            get {
                return ((string)(this["key_left_1"]));
            }
            set {
                this["key_left_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad4")]
        public string key_left_2 {
            get {
                return ((string)(this["key_left_2"]));
            }
            set {
                this["key_left_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpArrow")]
        public string key_up_1 {
            get {
                return ((string)(this["key_up_1"]));
            }
            set {
                this["key_up_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad8")]
        public string key_up_2 {
            get {
                return ((string)(this["key_up_2"]));
            }
            set {
                this["key_up_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RightArrow")]
        public string key_right_1 {
            get {
                return ((string)(this["key_right_1"]));
            }
            set {
                this["key_right_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad6")]
        public string key_right_2 {
            get {
                return ((string)(this["key_right_2"]));
            }
            set {
                this["key_right_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DownArrow")]
        public string key_down_1 {
            get {
                return ((string)(this["key_down_1"]));
            }
            set {
                this["key_down_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad2")]
        public string key_down_2 {
            get {
                return ((string)(this["key_down_2"]));
            }
            set {
                this["key_down_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public string key_select_1 {
            get {
                return ((string)(this["key_select_1"]));
            }
            set {
                this["key_select_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad5")]
        public string key_select_2 {
            get {
                return ((string)(this["key_select_2"]));
            }
            set {
                this["key_select_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public string key_exit_1 {
            get {
                return ((string)(this["key_exit_1"]));
            }
            set {
                this["key_exit_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public string key_exit_2 {
            get {
                return ((string)(this["key_exit_2"]));
            }
            set {
                this["key_exit_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string key_rescan_1 {
            get {
                return ((string)(this["key_rescan_1"]));
            }
            set {
                this["key_rescan_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string key_rescan_2 {
            get {
                return ((string)(this["key_rescan_2"]));
            }
            set {
                this["key_rescan_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string key_help_1 {
            get {
                return ((string)(this["key_help_1"]));
            }
            set {
                this["key_help_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string key_help_2 {
            get {
                return ((string)(this["key_help_2"]));
            }
            set {
                this["key_help_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Backspace")]
        public string key_back_1 {
            get {
                return ((string)(this["key_back_1"]));
            }
            set {
                this["key_back_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string key_back_2 {
            get {
                return ((string)(this["key_back_2"]));
            }
            set {
                this["key_back_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageUp")]
        public string key_pageup_1 {
            get {
                return ((string)(this["key_pageup_1"]));
            }
            set {
                this["key_pageup_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad9")]
        public string key_pageup_2 {
            get {
                return ((string)(this["key_pageup_2"]));
            }
            set {
                this["key_pageup_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageDown")]
        public string key_pagedown_1 {
            get {
                return ((string)(this["key_pagedown_1"]));
            }
            set {
                this["key_pagedown_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad3")]
        public string key_pagedown_2 {
            get {
                return ((string)(this["key_pagedown_2"]));
            }
            set {
                this["key_pagedown_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Home")]
        public string key_first_1 {
            get {
                return ((string)(this["key_first_1"]));
            }
            set {
                this["key_first_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad7")]
        public string key_first_2 {
            get {
                return ((string)(this["key_first_2"]));
            }
            set {
                this["key_first_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("End")]
        public string key_last_1 {
            get {
                return ((string)(this["key_last_1"]));
            }
            set {
                this["key_last_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad1")]
        public string key_last_2 {
            get {
                return ((string)(this["key_last_2"]));
            }
            set {
                this["key_last_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_launcher_1 {
            get {
                return ((string)(this["key_launcher_1"]));
            }
            set {
                this["key_launcher_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string key_launcher_2 {
            get {
                return ((string)(this["key_launcher_2"]));
            }
            set {
                this["key_launcher_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_settings_1 {
            get {
                return ((string)(this["key_settings_1"]));
            }
            set {
                this["key_settings_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string key_settings_2 {
            get {
                return ((string)(this["key_settings_2"]));
            }
            set {
                this["key_settings_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public string key_search_1 {
            get {
                return ((string)(this["key_search_1"]));
            }
            set {
                this["key_search_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem2")]
        public string key_search_2 {
            get {
                return ((string)(this["key_search_2"]));
            }
            set {
                this["key_search_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tab")]
        public string key_autocomplete_1 {
            get {
                return ((string)(this["key_autocomplete_1"]));
            }
            set {
                this["key_autocomplete_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_autocomplete_2 {
            get {
                return ((string)(this["key_autocomplete_2"]));
            }
            set {
                this["key_autocomplete_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public string key_cancel_1 {
            get {
                return ((string)(this["key_cancel_1"]));
            }
            set {
                this["key_cancel_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_cancel_2 {
            get {
                return ((string)(this["key_cancel_2"]));
            }
            set {
                this["key_cancel_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemPlus")]
        public string key_new_game_1 {
            get {
                return ((string)(this["key_new_game_1"]));
            }
            set {
                this["key_new_game_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string key_new_game_2 {
            get {
                return ((string)(this["key_new_game_2"]));
            }
            set {
                this["key_new_game_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delete")]
        public string key_delete_1 {
            get {
                return ((string)(this["key_delete_1"]));
            }
            set {
                this["key_delete_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_delete_2 {
            get {
                return ((string)(this["key_delete_2"]));
            }
            set {
                this["key_delete_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F9")]
        public string key_uninstall_1 {
            get {
                return ((string)(this["key_uninstall_1"]));
            }
            set {
                this["key_uninstall_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_uninstall_2 {
            get {
                return ((string)(this["key_uninstall_2"]));
            }
            set {
                this["key_uninstall_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F8")]
        public string key_make_shortcuts_1 {
            get {
                return ((string)(this["key_make_shortcuts_1"]));
            }
            set {
                this["key_make_shortcuts_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_make_shortcuts_2 {
            get {
                return ((string)(this["key_make_shortcuts_2"]));
            }
            set {
                this["key_make_shortcuts_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public string key_hide_game_1 {
            get {
                return ((string)(this["key_hide_game_1"]));
            }
            set {
                this["key_hide_game_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_hide_game_2 {
            get {
                return ((string)(this["key_hide_game_2"]));
            }
            set {
                this["key_hide_game_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F12")]
        public string key_favourite_1 {
            get {
                return ((string)(this["key_favourite_1"]));
            }
            set {
                this["key_favourite_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string key_favourite_2 {
            get {
                return ((string)(this["key_favourite_2"]));
            }
            set {
                this["key_favourite_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public string key_set_alias_1 {
            get {
                return ((string)(this["key_set_alias_1"]));
            }
            set {
                this["key_set_alias_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem7")]
        public string key_set_alias_2 {
            get {
                return ((string)(this["key_set_alias_2"]));
            }
            set {
                this["key_set_alias_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem5")]
        public string key_input_type_1 {
            get {
                return ((string)(this["key_input_type_1"]));
            }
            set {
                this["key_input_type_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_input_type_2 {
            get {
                return ((string)(this["key_input_type_2"]));
            }
            set {
                this["key_input_type_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem4")]
        public string key_grid_view_1 {
            get {
                return ((string)(this["key_grid_view_1"]));
            }
            set {
                this["key_grid_view_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem6")]
        public string key_grid_view_2 {
            get {
                return ((string)(this["key_grid_view_2"]));
            }
            set {
                this["key_grid_view_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6")]
        public string key_light_mode_1 {
            get {
                return ((string)(this["key_light_mode_1"]));
            }
            set {
                this["key_light_mode_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_light_mode_2 {
            get {
                return ((string)(this["key_light_mode_2"]));
            }
            set {
                this["key_light_mode_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public string key_image_display_1 {
            get {
                return ((string)(this["key_image_display_1"]));
            }
            set {
                this["key_image_display_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_image_display_2 {
            get {
                return ((string)(this["key_image_display_2"]));
            }
            set {
                this["key_image_display_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public string key_sort_method_1 {
            get {
                return ((string)(this["key_sort_method_1"]));
            }
            set {
                this["key_sort_method_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoName")]
        public string key_sort_method_2 {
            get {
                return ((string)(this["key_sort_method_2"]));
            }
            set {
                this["key_sort_method_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main Menu")]
        public string text_main_menu_title {
            get {
                return ((string)(this["text_main_menu_title"]));
            }
            set {
                this["text_main_menu_title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string text_settings_title {
            get {
                return ((string)(this["text_settings_title"]));
            }
            set {
                this["text_settings_title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Browse for folder")]
        public string text_browse_title {
            get {
                return ((string)(this["text_browse_title"]));
            }
            set {
                this["text_browse_title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This PC")]
        public string text_root_folder {
            get {
                return ((string)(this["text_root_folder"]));
            }
            set {
                this["text_root_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT THIS FOLDER")]
        public string text_select_folder {
            get {
                return ((string)(this["text_select_folder"]));
            }
            set {
                this["text_select_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE FOLDER HERE")]
        public string text_create_folder {
            get {
                return ((string)(this["text_create_folder"]));
            }
            set {
                this["text_create_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Select a platform.")]
        public string text_instruct1_platforms_nav_custom_msg {
            get {
                return ((string)(this["text_instruct1_platforms_nav_custom_msg"]));
            }
            set {
                this["text_instruct1_platforms_nav_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Press [Q] to exit;\\n Press [S] to rescan game collection;\\n Press H for help.")]
        public string text_instruct2_platforms_nav_custom_msg {
            get {
                return ((string)(this["text_instruct2_platforms_nav_custom_msg"]));
            }
            set {
                this["text_instruct2_platforms_nav_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Select a game.")]
        public string text_instruct1_games_nav_custom_msg {
            get {
                return ((string)(this["text_instruct1_games_nav_custom_msg"]));
            }
            set {
                this["text_instruct1_games_nav_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Press [Q] to exit;\\n Press [R] to return to previous menu;\\n Press [F] to add/re" +
            "move from favourites.")]
        public string text_instruct2_games_nav_custom_msg {
            get {
                return ((string)(this["text_instruct2_games_nav_custom_msg"]));
            }
            set {
                this["text_instruct2_games_nav_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Type name of a platform.")]
        public string text_instruct1_platforms_type_custom_msg {
            get {
                return ((string)(this["text_instruct1_platforms_type_custom_msg"]));
            }
            set {
                this["text_instruct1_platforms_type_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Enter \\\'/exit\\\' to quit;\\n Enter \\\'/help\\\' for more commands.")]
        public string text_instruct2_platforms_type_custom_msg {
            get {
                return ((string)(this["text_instruct2_platforms_type_custom_msg"]));
            }
            set {
                this["text_instruct2_platforms_type_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Type title of a game.")]
        public string text_instruct1_games_type_custom_msg {
            get {
                return ((string)(this["text_instruct1_games_type_custom_msg"]));
            }
            set {
                this["text_instruct1_games_type_custom_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Enter \\\'/exit\\\' to quit;\\n Enter \\\'/back\\\' to return to previous.")]
        public string text_instruct2_games_type_custom_msg {
            get {
                return ((string)(this["text_instruct2_games_type_custom_msg"]));
            }
            set {
                this["text_instruct2_games_type_custom_msg"] = value;
            }
        }
    }
}
